sudo: require
language: go
services:
 - docker

install:
# - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
# - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
# - sudo apt-get update
# - sudo apt-get install -y docker-engine
 - sudo docker pull ubuntu
 - sudo docker run -d -v $PWD:/work -w=/work ubuntu bash

script:
 - sudo apt-get install -y aptitude
 - sudo aptitude install -y devscripts cdbs dpkg-sig
 - debuild -uc -us --no-tgz-check
