sudo: require
language: go
services:
 - docker

install:
 - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
 - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
 - sudo apt-get update
 - sudo apt-get install -y docker-engine
 - sudo docker pull ubuntu
 - sudo docker run -e USER=$USER -e PASSWORD=$PASSWORD -e PKGNAME=$PKGNAME -e URL=$URL -e DIST=$DIST -e COMPONENT=$COMPONENT -e ARCHITECTURE=$ARCHITECTURE -v $PWD:/work -w=/work ubuntu bash -c "$CMD"

env:
 - CMD='apt-get install -y aptitude && aptitude install -y devscripts cdbs dpkg-sig && debuild --no-tgz-check -uc -us && curl -u${USER}:${PASSWORD} -XPUT "${URL}/${PKGNAME};deb.distribution=${DIST};deb.component=${COMPONENT};deb.architecture=${ARCHITECTURE}" -T ../${PKGNAME}'
